### ISSUE TITLE
爬取失败 <TITLE>302 Moved</TITLE>

### ISSUE THREAD

**Issue by ghost** [howie6879/MagicGoogle#1]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
如果 Google 自动检测到从您的计算机网络发出的请求可能违反服务条款，就会显示此网页。这些请求一旦停止，此阻断即会失效。
该流量可能是由恶意软件、浏览器插件或发送自动请求的脚本发出的。如果您与他人共享网络连接，请向管理员寻求帮助 — 这可能是由多台计算机使用同一 IP 地址导致的。了解详情
有时，如果您使用的是自动程序普遍使用的高级条款或者正在快速连续地发送请求，则可能会出现此网页。
=========================================================================
换了多次代理节点，还是不行，ops~

**Comment by howie6879** [comment]
readme.md

If  you need a big amount of querie but only having an ip address,I suggest  you can have a time lapse between 5s ~ 30s.

The reason that it always return empty might be as follows:


<H1>302 Moved</H1>

请问下你的节点是否是有效的  是不是已经被封过了？
