### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by L1uX1nZz** [howie6879/MagicGoogle#10]
您好，我使用了ss代理，可以正常翻墙，运行以后出现这个错误，请问是怎么一回事。
![bug3](https://user-images.githubusercontent.com/44453168/54470556-d5682a80-47e4-11e9-85bd-6a247d220f6e.PNG)

**Comment by howie6879** [comment]
代码里面也要用代理

L1uX1nZz <notifications@github.com> 于2019年3月16日周六 下午12:13写道：
