### ISSUE TITLE
求助。并不能返回搜索结果

### ISSUE THREAD

**Issue by ZhuojingXie** [howie6879/MagicGoogle#12]
你好，我试着运行您的示例。但是发现返回不了搜索结果，请问怎么解决？
对不起，初学者，烦劳

![image](https://user-images.githubusercontent.com/36093584/67260104-5740c600-f44e-11e9-8b8b-0f007fb43864.png)

**Comment by howie6879** [comment]
抱歉，本项目的规则失效了，有兴趣自己重新提取一下

**Comment by ZhuojingXie** [comment]
感谢您的迅速回复。再请问提取的思路应该是怎么样呢？

**Comment by howie6879** [comment]
就是从html里面提取目标字段

**Comment by ZhuojingXie** [comment]
明白。pyquery好像不可以用了。我是不是只有用BeautifulSoup?

**Comment by howie6879** [comment]
都行，能达到你的目的就行

ZhuojingXie <notifications@github.com> 于2019年10月22日周二 下午2:06写道：

**Comment by ZhuojingXie** [comment]
Thank you
