### ISSUE TITLE
magic_google求助

### ISSUE THREAD

**Issue by storm15041028** [howie6879/MagicGoogle#17]
您好，我使用下面的语句for k in mg.search(query="MoBiSys 2021", num=10, language='en'):
                                                                pprint.pprint(k)
想搜索MobiSys 2021关键字下谷歌搜索的前10个结果，但每次输出的结果的数量都不相同。而且有的时候输出结果中的text这一项的长度也会发生变化，请问下这是什么原因导致的。

**Comment by howie6879** [comment]
域名自动变化
