### ISSUE TITLE
Can not response result properly.

### ISSUE THREAD

**Issue by jackzhang8806** [howie6879/MagicGoogle#2]
My debug result is that 
u'<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF="https://www.google.com.au/search?hl=en&amp;q=python&amp;btnG=Search&amp;gbv=1&amp;gws_rd=cr&amp;ei=ZFxwWfyJC4bo0ASS0Ie4Ag">here</A>.\r\n</BODY></HTML>\r\n'

If I run the script directly, just show the link 2017-07-20 17:07:08,892 - magic_google - INFO: https://www.google.com/search?hl=en&q=python&btnG=Search&gbv=1.

It doesn't appear any more information. 

Could Google detect the searching script?

**Comment by howie6879** [comment]
If  you need a big amount of querie but only having an ip address,I suggest  you can have a time lapse between 5s ~ 30s.

The reason that it always return empty might be as follows:

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://ipv4.google.com/sorry/index?continue=https://www.google.me/s****">here</A>.
</BODY></HTML>


At the same time, I hope you can use your own vpn

**Comment by jackzhang8806** [comment]
I setup pause as 30s, but still the same result. 

And nothing should be shown on the screen. 

Just search link on the screen.

**Comment by howie6879** [comment]
First, i think you need a reliable proxy.

And then setup pause 15~30s is enough.

**Comment by jackzhang8806** [comment]
I do not use the proxy.

I already changed pause as 30s and I think it should be enough.

**Comment by howie6879** [comment]
That's right, but your ip is not reliable

You just need a reliable proxy.

That's why you can't get a response result properly.

**Comment by jackzhang8806** [comment]
Thanks for your help.

I will use another IP to test it.

**Comment by howie6879** [comment]
In my opinion ,i suggest you can have a  proxy to do this job specifically

**Comment by jackzhang8806** [comment]
I am in Aus, so I think I do not need any proxy to access Google. 

Anyway, I will test it to use another IP.

**Comment by howie6879** [comment]
I know you can access Google without proxy.

I mean the proxy is very useful to avoid being blocked by Google

It's better than your ip.

**Comment by jackzhang8806** [comment]
I tried it by using the browser, but it redirected to another URL. 

I think there might be a trick.

**Comment by howie6879** [comment]
That 's why i suggest you should use a reliable proxy.

you can visit this url:
https://support.google.com/websearch/answer/86640?hl=en
