### ISSUE TITLE
can't find 'data' folder

### ISSUE THREAD

**Issue by pkwv2012** [howie6879/MagicGoogle#3]
environment: Ubuntu 16.04 installed by pip 
python version: 2 or 3(neither work)

**Comment by howie6879** [comment]
Can you provide more detailed logs?

**Comment by pkwv2012** [comment]
`ls /usr/local/lib/python2.7/dist-packages/MagicGoogle`
result is
`> config.py  config.pyc  __init__.py  __init__.pyc  magic_google.py  magic_google.pyc`
can't find the `data` folder

when calling `get_random_domain()`, the return value is always "www.google.com", 
cause there is no `data` folder and `all_domain.txt` file under the installed path.

**Comment by howie6879** [comment]
Thanks for your issue, you can use the latest version v0.2.6 : https://pypi.python.org/pypi/MagicGoogle/0.2.6
<img width="406" alt="screen shot 2017-11-03 at 21 04 02" src="https://user-images.githubusercontent.com/17047388/32374988-ee685cd0-c06d-11e7-96c0-8e7af55c21b5.png">

**Comment by pkwv2012** [comment]
works well~
