### ISSUE TITLE
Max of return in URL's

### ISSUE THREAD

**Issue by ctoveloz** [howie6879/MagicGoogle#5]
Can I change to get more than 9 URL results?
he get the result from the following pages? 2,3,4,5,6....

Thanks.

**Comment by howie6879** [comment]
Sorry I did not get the next page result

But you can get more than 9 URL results

For example:

``` python
for i in mg.search(query='python', num=99):
    pprint.pprint(i)
```

**Comment by howie6879** [comment]
Perhaps I will realize this issue later
