### ISSUE TITLE
请教：关于url获取的问题

### ISSUE THREAD

**Issue by jimmy-walker** [howie6879/MagicGoogle#7]
您好，我看了您的文章[对于python抓取google搜索结果的一些了解](http://blog.howie6879.cn/post/14/)。感谢您分享此项目。
我的疑问您是怎么通过浏览器的审查内容找到这个url的（https://{domain}/search?hl={language}&q={query}&btnG=Search&gbv=1）。
我以前写python爬虫都是直接从html中解析哪些标签的结果，得到所要的内容，对于这种url获取的方法不是很了解，请问能否有相关的教程或是文章推荐的吗？
期待你的回复谢谢。

**Comment by howie6879** [comment]
看浏览器url显示就好了
