### ISSUE TITLE
不同google搜索结果数量不同

### ISSUE THREAD

**Issue by eee-du** [howie6879/MagicGoogle#8]
当我搜索“lion”+"mammal"时已知google.rw结果为60900000，而google.com结果为61100000
请问是url的设置问题吗？

**Comment by howie6879** [comment]
对

**Comment by eee-du** [comment]
有没有办法可以让其他的domain的搜索结果都一样？比如说搜索同一个关键字 ，搜索结果都和google.com搜索出来的结果数一样

**Comment by howie6879** [comment]
只能只用 google.com 才可以
