### ISSUE TITLE
实测 user_agents.txt 中的一些 header 会一定概率不可用

### ISSUE THREAD

**Issue by wuqxuan** [howie6879/MagicGoogle#9]

**Comment by howie6879** [comment]
怎么说？

**Comment by wuqxuan** [comment]
就是一些 header 去请求，拿不到东西，不知道你们有没有遇到这种问题？

**Comment by howie6879** [comment]
可以具体哪个ua么 能确定问题是出在ua上么 还是domain有问题

**Comment by wuqxuan** [comment]
不好意思，表述有误，刚才仔细看了下，Opera 打头的 ua 返回的搜索结果链接（<h3 class="r"><a href="/url?url=https://）和其他 ua 返回的不一样（<h3 class="r"><a href="/url?q=https:），不是拿不到东西，而是我的正则匹配没有做适应，问题解决了。
